name: '[Template] Release'

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        description: 'The name of the mod (e.g Signs)'
        required: true
      project-namespace:
        type: string
        description: 'The namespace of the project (e.g jcdcdev)'
        required: true
      project-description:
        type: string
        description: 'The description of the project'
        required: true
      project-url:
        type: string
        description: 'The url of the project'
        required: true
      project-community:
        type: string
        description: 'The community of the project'
        required: true
      project-categories:
        type: string
        description: 'The categories of the project'
        required: true
      project-dependencies:
        type: string
        description: 'The dependencies of the project'
        required: true
      project-version:
        type: string
        description: 'The version of the mod'
        required: true
      asset-name:
        type: string
        description: 'The name of the asset'
        required: true

env:
  PROJECT_NAMESPACE: ${{ inputs.project-namespace }}
  MOD_NAME: ${{ inputs.project-name }}
  PROJECT_DESCRIPTION: ${{ inputs.project-description }}
  PROJECT_URL: ${{ inputs.project-url }}
  PROJECT_COMMUNITY: ${{ inputs.project-community }}
  PROJECT_CATEGORIES: ${{ inputs.project-categories }}
  PROJECT_DEPENDENCIES: ${{ inputs.project-dependencies }}
  MOD_VERSION: ${{ inputs.project-version }}
  ASSET_NAME: ${{ inputs.asset-name }}
  MOD_PATH: ${{ github.workspace }}/mod
  THUNDERSTORE_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}
jobs:
  create-release:
    name: create release ${{ inputs.project-name }} - ${{ inputs.project-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create tag
        shell: bash
        run: |
          PREVIOUS_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo '')
          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git tag -fa ${{ env.MOD_VERSION }} -m "Release ${{ env.MOD_VERSION }}"
          git push --force origin ${{ env.MOD_VERSION }}
      - uses: jcdcdev/jcdcdev.Github.GenerateChangelog@main
        id: changelog
        with:
          target-version: ${{ env.MOD_VERSION }}
          previous-version: ${{ env.PREVIOUS_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ASSET_NAME }}
          path: ${{ env.MOD_PATH }}
      - name: Update changelog
        id: update-changelog
        env:
          CHANGELOG: |
            ## ${{ env.MOD_VERSION }}
            
            ${{ steps.changelog.outputs.changelog }}
        run: |
          {
            echo 'changelog<<EOF'
            echo "${CHANGELOG}"
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Create changelog file
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_CHANGELOG: ${{ steps.update-changelog.outputs.changelog }}
          REPO: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
        run: |
          $changelog_file = "${{ env.MOD_PATH }}/CHANGELOG.md"
          if (Test-Path $changelog_file) {
            Write-Host "Changelog already exists"
            exit 0
          }
          
          New-Item -Path $changelog_file -ItemType File -Force

          $jq = "sort_by(.tag_name) | reverse | .[]" 
          $releases = gh api "repos/${{ env.REPO }}/releases" --jq "$jq" | ConvertFrom-Json
          
          $changelog="# Changelog`n${{ env.LATEST_CHANGELOG }}"          
          $releases | ForEach-Object {
            $release = $_
            $body = $release.body
            $body = $body -replace '\r\n', "`n"
            write-host "$body"
            $changelog += "`n$body"
          }

          $terms = 'close', 'closes', 'closed', 'fix', 'fixes', 'fixed', 'resolve', 'resolves', 'resolved'
          $terms | ForEach-Object {
            $changelog = $changelog -replace "($_ #(\d+))", '[Issue #$2](https://github.com/${{ env.REPO }}/issues/$2)'
          }
          
          $changelog = $changelog -replace '\n', "`n"
          Set-Content -Path $changelog_file -Value $changelog -NoNewline
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.MOD_PATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.MOD_VERSION }}
          tag: ${{ env.MOD_VERSION }}
          body: ${{ steps.update-changelog.outputs.changelog }}
      - name: Create icon and README
        shell: pwsh
        run: |
          $files = @('icon.png', 'README.md')
          $files | ForEach-Object {
              $file = $_
              $path = "${{ env.MOD_PATH }}/$file"
              if (Test-Path $file) {              
                if (-not (Test-Path $path)) {
                  Write-Host "Copying $file to $path"
                  Copy-Item $file $path
                }
              }
          }
      - name: Verify Package
        shell: pwsh
        run: |
          $path = "${{ env.MOD_PATH }}"
          $files = Get-ChildItem -Path $path -Recurse
          Write-Host "Files to package:`n`n$files"       
          $dlls = $files | Where-Object { $_.Extension -eq '.dll' }
          if ($dlls.Count -eq 0) {
            Write-Error "No dlls found in $path"
            exit 1
          }
      - uses: GreenTF/upload-thunderstore-package@87a940b1f508ab1a6866eded55a9539afdf09792
        id: push-to-thunderstore
        with:
          token: ${{ env.THUNDERSTORE_TOKEN }}
          community: ${{ env.PROJECT_COMMUNITY }}
          namespace: ${{ env.PROJECT_NAMESPACE }}
          name: ${{ env.MOD_NAME }}
          description: ${{ env.PROJECT_DESCRIPTION }}
          version: ${{ env.MOD_VERSION }}
          path: ${{ env.MOD_PATH }}
          categories: ${{ env.PROJECT_CATEGORIES }}
          website: ${{ env.PROJECT_URL }}
          deps: ${{ env.PROJECT_DEPENDENCIES }}