name: '🚀 Release mod'
run-name: >
  release ${{github.repository}} #${{ github.run_number }}

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run the release'
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      project-name: jcdcdev.Valheim.Signs
  release:
    uses: ./.github/workflows/release-template.yml
    needs:
      - build
    permissions:
      contents: write
    with:
      project-name: Signs
      project-namespace: jcdcdev
      project-description: "Add information about your world to signs! Easy to configure and use."
      project-url: "https://github.com/jcdcdev/jcdcdev.Valheim.Signs"
      project-community: "valheim"
      project-categories: |
        mods
        client-side
        tweaks
        server-side
      project-version: ${{ needs.build.outputs.mod-version }}
      asset-name: ${{ needs.build.outputs.asset-name }}
      project-dependencies: ${{ needs.build.outputs.mod-dependencies }}
      nexus-mod-game: "valheim"
    secrets: inherit
